spring:
  application:
    name: sample-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud-sample?useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kevin
    filters: stat,wall
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    schema: classpath:schema.sql
  jpa:
    show-sql: true
server:
  port: 7500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
      # 访问实例是，需要 主机IP+端口，如下配置主机为对应的ip
      hostname: ${spring.cloud.client.ipAddress}
      #  Instance ID 默认值是:${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true
api:
  title: ${spring.application.name} RESTFUL 接口文档
  descn: ${spring.application.name}是spring cloud sample项目中的订单微服务
  author:
    name: Kevin无道
    url: https://github.com/kevin-gm/learning_demo/tree/master/cloud-sample/sample-order
    email: aa@qq.com
  version: 1.0
  service-url: http://localhost:${server.port}/swagger-ui.html
test:
  bus:
    value: kevin-gm-gg-ll-kk-aa